wip

diff --git a/tmpl/profile b/tmpl/profile
--- a/tmpl/profile
+++ b/tmpl/profile
@@ -1,7 +1,19 @@
 export MY_LINUX_SETUP=1
 
+# make sure we're running bash
+if [ -z "$BASH_VERSION" ]; then
+  echo "error: not a bash shell"
+  exit 1
+fi
+
+# TODO parameterize hostname and user config names
+export LINUX_HOSTNAME=odin
+export USER_CONFIG=~/.profile
 export EDITOR=/usr/bin/vim
 export VISUAL=/usr/bin/vim
+
+# shouldn't need to set this explicitly, but nvm defaults to ~/.nvm if not set
+export XDG_CONFIG_HOME=~/.config
 
 #
 # Aliases
@@ -10,22 +22,16 @@ alias l="ls -ChF --group-directories-first"
 alias l="l -A"
 alias ll="la -l"
 
-alias gs="git status"
 alias gb="git branch"
 alias gc="git checkout"
+alias gr="git rebase"
+alias gri="gr -i"
+alias gs="git status -u"
+alias gv="git remote -v"
 
-#
-# PS1 prompt
-#
-parse_git_branch() {
-  git branch --show-current 2>/dev/null | sed -e 's/\(.*\)/ (\1)/'
-}
-
-prompt_generator() {
-        export PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(parse_git_branch)\n\$ "
-}
-
-export PROMPT_COMMAND=prompt_generator
+# clear scrollback
+alias cs="printf '\e[3J'"
+alias ccs="clear && cs"
 
 # go
 export PATH=$PATH:/usr/local/go/bin
@@ -39,3 +45,6 @@ export NVM_DIR="$HOME/.nvm"
 [ -f ~/.fzf.bash ] && source ~/.fzf.bash
 [ -f ~/bin/tl-completion.bash ] && source ~/bin/tl-completion.bash
 [ -f ~/.config/completions/deno.bash ] && source ~/.config/completions/deno.bash
+
+# TODO parameterize
+source ~/.tony.prompt
